platform :ios, '12.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

def networking_pods
  pod 'FirebaseCore', '~> 8'
  pod 'FirebaseFirestore', '~> 8'
  pod 'FirebaseStorage', '~> 8'
  pod 'FirebaseAuth', '~> 8'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Email'
end

def ui_pods
  pod 'MessageKit', '= 3.4.2'
end

target 'ChatApp' do
  networking_pods
  ui_pods

  pod 'SwiftLint', '~> 0.40'
end

target 'Chat' do
  ui_pods
end

target 'ChatNetworkingFirestore' do
  networking_pods
end

target 'ChatUI' do
  ui_pods
end

# Workaround for Xcode 12 to set deployment targets greater than or equal to iOS 9.0
post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].split('.')[0].to_i < 9
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
       end
     end
   end
end
