# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!
inhibit_all_warnings!

def networking_pods
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestoreSwift'
end

def ui_pods
  pod 'MessageKit'
end

target 'ChatApp' do
  networking_pods
end

target 'Chat' do
  networking_pods
end

target 'ChatNetworkingFirestore' do
  networking_pods
end

target 'ChatUI' do
  ui_pods
end
